### ISSUE TITLE
Solicitud de libro.

### ISSUE THREAD

**Issue by ejdecena** [escalise/AI_Course_PG#1]
# Solicitud de Libro.

Saludos profesor Scalise. Si puede por favor incorporar al repositorio el libro de *Algoritmos Genéticos con Python* de Clinton Sheppard.
Gracias de antemano.

**Comment by escalise** [comment]
Hola,

Disculpa, no había visto esto. No creo que pueda poner público el libro, pero te dejo un enlace para que lo descargues -> https://drive.google.com/open?id=1U5-PXjSaLiPZsMXgX9GRWbndpsoeYTrR

¿Estás haciendo las asignaciones del curso?

Saludos

**Comment by ejdecena** [comment]
Saludos profe, gracias por el link. Actualmente programo Machine Learning con Python y otras cosillas :-)

**Comment by escalise** [comment]
chévere.
